###
GET http://localhost:3000/api/todos
Accept: application/json

###

POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "userId": 1,
  "title": "Faire le repas du soir",
  "completed": true
}

###

GET http://localhost:3000/api/todos/1
Accept: application/json

###


DELETE http://localhost:3000/api/todos/1
Accept: application/json

###

GET http://localhost:3000/api/todos/1000
Accept: application/json

###

DELETE http://localhost:3000/api/todos/1000
Accept: application/json
