POST http://localhost:3000/api/user/sign-in
Content-Type: application/json

{
  "mail": "frizzarin.n@sfeir.com",
  "password": "sfeir"
}

###

GET http://localhost:3000/api/user/token
Accept: application/json
